"""Module 1 - The Socratic Hypothesis & Metric Engine.

Reads a PRD (or a few interactive answers) and produces a validated
``AnalyticsBlueprint``: the primary metric, guardrails, hypotheses, and a clean
A/B experiment design.
"""

from __future__ import annotations

import json

from ..core.schemas import AnalyticsBlueprint
from ..llm import LLMClient
from ..prompts import HYPOTHESIS_SYSTEM

# The handful of questions that, answered, stand in for a PRD.
SOCRATIC_QUESTIONS = [
    ("feature", "What feature are you launching, in one sentence?"),
    ("action", "What is the core user action it should drive?"),
    ("counter", "What metric might it accidentally hurt (the counter-metric)?"),
    ("audience", "Who is the target user?"),
]


def _user_prompt(prd_text: str) -> str:
    schema = json.dumps(AnalyticsBlueprint.model_json_schema())
    return (
        f"PRD:\n\"\"\"\n{prd_text.strip()}\n\"\"\"\n\n"
        f"Produce the metric plan as JSON matching this schema:\n{schema}"
    )


def generate_blueprint(prd_text: str, llm: LLMClient) -> AnalyticsBlueprint:
    """Turn raw PRD markdown into a validated blueprint."""
    return llm.complete_json(HYPOTHESIS_SYSTEM, _user_prompt(prd_text), AnalyticsBlueprint)


_GOOD = {"increase": "higher is better", "decrease": "lower is better"}


def render_blueprint_doc(bp: AnalyticsBlueprint) -> str:
    """A friendly, readable version of the blueprint for a PM to review at the gate."""
    h = bp.hypotheses
    lines = [
        f"# Metric Plan: {bp.feature_name}",
        "",
        f"> {bp.summary}",
        "",
        "_This is the plan we will measure against. If anything looks off, edit_ "
        "`metric_plan.yaml` _(the machine-readable file next to this one) and re-run_ "
        "`prd-to-readout metric`.",
        "",
        "## The bet",
        "",
        f"- **If we** {h.if_we or bp.summary}",
        f"- **Then we will see** {h.then_observe or h.alternative}",
        f"- **Because** {h.because or 'n/a'}",
        f"- **We can detect** a {bp.experiment.mde:.0%} relative change at 80% power.",
        "",
        "## Primary metric (the one that decides ship or not)",
        "",
        f"**{bp.primary_metric.name}** ({bp.primary_metric.type}, {_GOOD.get(bp.primary_metric.direction, '')})",
        "",
        f"{bp.primary_metric.description}",
        "",
        f"_How it is computed:_ {bp.primary_metric.formula}",
        "",
    ]

    if bp.guardrail_metrics:
        lines += ["## Guardrails (must not get worse)", "",
                  "| Metric | Type | What good looks like | Definition |",
                  "|---|---|---|---|"]
        for m in bp.guardrail_metrics:
            lines.append(f"| `{m.name}` | {m.type} | {_GOOD.get(m.direction, '')} | {m.description} |")
        lines.append("")

    if bp.health_metrics:
        lines += ["## Health to watch after launch", "",
                  "| Metric | Kind | Alert if above |", "|---|---|---|"]
        for hm in bp.health_metrics:
            unit = hm.unit or ""
            lines.append(f"| `{hm.name}` | {hm.kind} | {hm.threshold:g}{unit} |")
        lines.append("")

    exp = bp.experiment
    lines += [
        "## How we will test it",
        "",
        f"- {exp.control_arm} vs {exp.treatment_arm}, {exp.treatment_split:.0%} in treatment",
        f"- About {exp.users_per_arm:,} users per group, over {exp.horizon_days} days",
        "",
    ]

    ap = bp.approvers
    if ap.product or ap.engineering or ap.data_science:
        who = []
        if ap.product:
            who.append(f"Product @{ap.product}")
        if ap.engineering:
            who.append(f"Engineering @{ap.engineering}")
        if ap.data_science:
            who.append(f"Data Science @{ap.data_science}")
        lines += ["## Approvers", "", ", ".join(who), ""]

    lines += ["---", "*Generated by prd-to-readout from your PRD. "
              "Source of truth: metric_plan.yaml.*", ""]
    return "\n".join(lines)


def prd_from_answers(answers: dict[str, str]) -> str:
    """Synthesize a mini-PRD from Socratic survey answers."""
    lines = ["# Feature brief", "", answers.get("feature", "").strip(), ""]
    if answers.get("action"):
        lines += ["## Core user action", answers["action"].strip(), ""]
    if answers.get("counter"):
        lines += ["## Counter-metric to protect", answers["counter"].strip(), ""]
    if answers.get("audience"):
        lines += ["## Target users", answers["audience"].strip(), ""]
    return "\n".join(lines)
