"""Module 2 - Automated Tracking & Logging Specification.

From the blueprint, infer the minimal events needed to compute every metric and
emit a Segment/Amplitude-style schema plus paste-ready logger snippets.
"""

from __future__ import annotations

import json

from ..core.schemas import AnalyticsBlueprint, EventSpec, TrackingSchema
from ..llm import LLMClient
from ..prompts import LOGGING_SYSTEM

_TS_TYPES = {"string": "string", "number": "number", "boolean": "boolean", "timestamp": "string"}
_PY_TYPES = {"string": "str", "number": "float", "boolean": "bool", "timestamp": "str"}


def _user_prompt(bp: AnalyticsBlueprint) -> str:
    schema = json.dumps(TrackingSchema.model_json_schema())
    return (
        f"Analytics blueprint:\n{bp.to_yaml()}\n\n"
        f"Design the tracking schema and metric bindings as JSON matching:\n{schema}"
    )


def generate_tracking_schema(bp: AnalyticsBlueprint, llm: LLMClient) -> TrackingSchema:
    return llm.complete_json(LOGGING_SYSTEM, _user_prompt(bp), TrackingSchema)


def _pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _ts_snippet(event: EventSpec) -> str:
    fields = "; ".join(f"{p.name}: {_TS_TYPES[p.type]}" for p in event.properties)
    props_type = f"{{ {fields} }}" if fields else "{}"
    fn = f"track{_pascal(event.name)}"
    return (
        f"// {event.description}\n"
        f"export function {fn}(userId: string, arm: string, props: {props_type}) {{\n"
        f"  analytics.track('{event.name}', {{ user_id: userId, arm, ...props }});\n"
        f"}}\n"
    )


def _py_snippet(event: EventSpec) -> str:
    args = "".join(f", {p.name}: {_PY_TYPES[p.type]}" for p in event.properties)
    payload = ", ".join([f'"{p.name}": {p.name}' for p in event.properties])
    fn = f"track_{event.name}"
    return (
        f"# {event.description}\n"
        f"def {fn}(user_id: str, arm: str{args}):\n"
        f'    analytics.track(user_id, "{event.name}", '
        f'{{"arm": arm{", " + payload if payload else ""}}})\n'
    )


def render_snippets(schema: TrackingSchema) -> dict[str, str]:
    """Return {filename: contents} for paste-ready logger calls."""
    ts = "// Auto-generated by prd-to-readout. Paste into your frontend.\n\n"
    ts += "\n".join(_ts_snippet(e) for e in schema.events)
    py = "# Auto-generated by prd-to-readout. Paste into your backend.\n\n"
    py += "\n".join(_py_snippet(e) for e in schema.events)
    return {"track.ts": ts, "track.py": py}


def render_spec_doc(bp: AnalyticsBlueprint, schema: TrackingSchema) -> str:
    """A human-readable logging spec: the deliverable an engineer implements from."""
    lines = [
        f"# Logging Spec: {bp.feature_name}",
        "",
        f"> {bp.summary}",
        "",
        "Implement the events below so the analytics metrics can be computed. Every event "
        "must also carry `user_id` (string), `arm` (string, the experiment group), and "
        "`timestamp`. Snippets are in `snippets/track.ts` and `snippets/track.py`.",
        "",
        "## Events",
        "",
    ]
    for ev in schema.events:
        supports = [b.metric_name for b in schema.bindings if b.event_name == ev.name]
        lines.append(f"### `{ev.name}`")
        lines.append("")
        lines.append(ev.description)
        if supports:
            lines.append("")
            lines.append(f"Supports metric(s): {', '.join(f'`{m}`' for m in supports)}")
        lines.append("")
        if ev.properties:
            lines.append("| Property | Type | Required | Notes |")
            lines.append("|---|---|---|---|")
            for p in ev.properties:
                lines.append(f"| `{p.name}` | {p.type} | {'yes' if p.required else 'no'} | {p.description} |")
        else:
            lines.append("_No extra properties beyond the standard fields._")
        lines.append("")
    lines += [
        "## Implementation checklist",
        "",
        "- [ ] Fire each event at the right moment in the product flow",
        "- [ ] Include `user_id`, `arm`, and `timestamp` on every event",
        "- [ ] Match property names and types exactly (they drive the SQL)",
        "- [ ] Verify events reach your analytics sink (Segment/Amplitude/warehouse)",
        "- [ ] Reply / mark the handoff done so QA can verify the data",
        "",
        "_Generated by prd-to-readout._",
    ]
    return "\n".join(lines)
