"""The recurring monitor (DAILY_PULSE.md): adoption, engagement, and health watch.

Runs as often as you like (cheap and deterministic, no LLM). It tracks how the
launch is being adopted and flags operational regressions (latency spikes,
crash/ANR increases). It deliberately makes NO ship decision. The decision lives
in the one-off READOUT.md.
"""

from __future__ import annotations

from ..core import health as health_mod
from ..core.health import HealthAlert
from ..core.provenance import RunContext
from ..core.schemas import AnalyticsBlueprint
from ..core.stats import StatResult
from .report_agent import _fmt

_SEV_EMOJI = {"ok": "🟢", "watch": "🟡", "regression": "🔴"}


def _status(alerts: list[HealthAlert], results: list[StatResult]) -> tuple[str, str]:
    h = health_mod.overall_status(alerts)
    primary = next((r for r in results if r.is_primary), None)
    adoption_bad = bool(primary and primary.significant and not primary.moved_favorably)
    if h == "regression" or adoption_bad:
        return "🔴", "REGRESSION"
    if h == "watch":
        return "🟡", "WATCH"
    return "🟢", "HEALTHY"


def _adoption_table(results: list[StatResult]) -> str:
    head = (
        "| Metric | Role | Control | Treatment | Change |\n"
        "|---|---|---|---|---|"
    )
    rows = []
    for r in results:
        if not (r.is_primary or r.role == "adoption"):
            continue
        role = "primary" if r.is_primary else "engagement"
        rows.append(
            f"| `{r.metric_name}` | {role} | {_fmt(r.metric_type, r.control_value)} "
            f"| {_fmt(r.metric_type, r.treatment_value)} | {r.relative_lift * 100:+.1f}% |"
        )
    return "\n".join([head, *rows]) if rows else "_No adoption metrics._"


def _fmt_health(value: float, unit: str) -> str:
    if unit == "%":
        return f"{value:.2f}%"
    return f"{value:.0f}{unit}" if unit else f"{value:.1f}"


def _health_table(alerts: list[HealthAlert]) -> str:
    if not alerts:
        return "_No health metrics configured for this feature._"
    head = (
        "| Health Metric | Kind | Recent | Threshold | Baseline | Status |\n"
        "|---|---|---|---|---|---|"
    )
    rows = []
    for a in alerts:
        rows.append(
            f"| `{a.name}` | {a.kind} | {_fmt_health(a.observed, a.unit)} "
            f"| {_fmt_health(a.threshold, a.unit)} | {_fmt_health(a.baseline, a.unit)} "
            f"| {_SEV_EMOJI.get(a.severity, '')} {a.severity} |"
        )
    return "\n".join([head, *rows])


def _regression_callouts(alerts: list[HealthAlert]) -> list[str]:
    out = []
    for a in alerts:
        if a.severity == "regression":
            out.append(
                f"- 🔴 **{a.name}** ({a.kind}) is {_fmt_health(a.observed, a.unit)} vs a "
                f"{_fmt_health(a.threshold, a.unit)} threshold (baseline {_fmt_health(a.baseline, a.unit)}). "
                "Likely a launch regression; page the on-call owner."
            )
        elif a.severity == "watch":
            out.append(
                f"- 🟡 **{a.name}** ({a.kind}) is trending up "
                f"({_fmt_health(a.observed, a.unit)} vs baseline {_fmt_health(a.baseline, a.unit)}). Keep watching."
            )
    return out


def generate_pulse(bp: AnalyticsBlueprint, results: list[StatResult], alerts: list[HealthAlert],
                   charts: str, ctx: RunContext | None, *, generated_at: str) -> str:
    """Render `DAILY_PULSE.md`: the deterministic adoption + health monitor.

    No LLM call, so it is safe to schedule. The status badge is the worst of the
    health signals and adoption; simulated runs are banner-labeled and it makes
    no ship decision (that lives in the readout).
    """
    badge, label = _status(alerts, results)
    callouts = _regression_callouts(alerts)
    banner = []
    if ctx is not None and ctx.is_simulated:
        banner = ["> ⚠️ **SIMULATED PREVIEW**: monitoring a simulated stream to validate the setup.", ""]
    lines = [
        f"# 📡 Daily Pulse: {bp.feature_name}",
        "",
        "> Adoption, engagement, and health monitoring. The ship/kill/iterate decision lives in READOUT.md.",
        "",
        *banner,
        f"## {badge} Status: {label}",
        "",
        f"_As of {generated_at}._",
        "",
        "## Adoption & Engagement",
        "",
        _adoption_table(results),
        "",
        "## Health & Regressions",
        "",
        _health_table(alerts),
        "",
        *(["### ⚠️ Active alerts", "", *callouts, ""] if callouts else []),
        "## Trends",
        "",
        "```",
        charts.rstrip(),
        "```",
        "",
        "---",
        "*Generated by prd-to-readout. Monitoring only; the launch decision is in READOUT.md.*",
        "",
    ]
    return "\n".join(lines)
