// Auto-generated by prd-to-readout. Paste into your frontend.

// Fired when a user completes payment for an order.
export function trackOrderCompleted(userId: string, arm: string, props: { amount: number }) {
  analytics.track('order_completed', { user_id: userId, arm, ...props });
}

// Fired when a user cancels within the 5-second undo window.
export function trackOrderCancelled(userId: string, arm: string, props: {}) {
  analytics.track('order_cancelled', { user_id: userId, arm, ...props });
}

// Fired when a user completes checkout via the one-tap button.
export function trackOneTapUsed(userId: string, arm: string, props: {}) {
  analytics.track('one_tap_used', { user_id: userId, arm, ...props });
}
