"""Logging QA: prove the logging is actually live and correct.

This is the step that's missing from a one-shot demo and the one a data scientist
most needs before trusting any number. Once events exist in the source, it checks
that every declared event is arriving, required properties are populated, both arms
have volume, and there's no sample-ratio mismatch. Its pass/fail gates the pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from . import stats
from .duckdb_runner import DuckDBRunner
from .schemas import AnalyticsBlueprint, TrackingSchema


@dataclass
class QACheck:
    name: str
    passed: bool
    detail: str = ""
    critical: bool = True  # critical failures block the gate; non-critical only warn


@dataclass
class QAReport:
    checks: list[QACheck] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        """True if every critical check passed (non-critical checks only warn)."""
        return all(c.passed for c in self.checks if c.critical)

    @property
    def warnings(self) -> list[QACheck]:
        """The failed-but-non-critical checks: worth a look, but they don't block."""
        return [c for c in self.checks if not c.passed and not c.critical]


def run_qa(runner: DuckDBRunner, bp: AnalyticsBlueprint, tracking: TrackingSchema) -> QAReport:
    """Run the logging-trust checks against ingested events and return a report.

    Verifies that every declared event is arriving, required properties are
    populated (>=99%, non-critical), both arms have users, and there is no
    sample-ratio mismatch. The report's ``passed`` gates the pipeline.
    """
    checks: list[QACheck] = []
    con = runner.con

    present = {r[0] for r in runner.query("SELECT DISTINCT event_name FROM raw_events")}

    # 1. Every declared event is arriving.
    for ev in tracking.events:
        ok = ev.name in present
        checks.append(QACheck(f"event '{ev.name}' is arriving", ok,
                              "" if ok else "no rows for this event"))

    # 2. Required properties are populated.
    for ev in tracking.events:
        if ev.name not in present:
            continue
        for p in ev.properties:
            if not p.required:
                continue
            total, nn = con.execute(
                f"SELECT count(*), count(*) FILTER (WHERE props->>'{p.name}' IS NOT NULL) "
                "FROM raw_events WHERE event_name = ?",
                [ev.name],
            ).fetchone()
            frac = (nn / total) if total else 0.0
            checks.append(QACheck(
                f"{ev.name}.{p.name} populated", frac >= 0.99, f"{frac:.1%} non-null",
                critical=False,
            ))

    # 3. Both arms have users.
    arm_counts = {r[0]: r[1] for r in runner.query(
        "SELECT arm, count(DISTINCT user_id) FROM raw_events GROUP BY arm"
    )}
    exp = bp.experiment
    nc, nt = arm_counts.get(exp.control_arm, 0), arm_counts.get(exp.treatment_arm, 0)
    ok = nc > 0 and nt > 0
    detail = f"{exp.control_arm}={nc}, {exp.treatment_arm}={nt}"
    if not ok and arm_counts:
        # The expected labels are missing: show what the data actually uses so a
        # control/treatment vs A/B mismatch is obvious instead of a bare "0, 0".
        found = ", ".join(f"{a}={c}" for a, c in sorted(arm_counts.items()))
        detail += f" (arms present: {found})"
    checks.append(QACheck("both arms have users", ok, detail))

    # 4. Sample-ratio-mismatch.
    srm = stats.srm_check(nc, nt, exp.treatment_split)
    checks.append(QACheck("no sample-ratio mismatch (SRM)", srm["passed"],
                          f"p={srm['p_value']:.4f} (chisq={srm['chisq']:.1f})"))

    return QAReport(checks)


def render_qa_report(report: QAReport, bp: AnalyticsBlueprint) -> str:
    """Render the QA report as the human-readable `LOGGING_QA.md` markdown."""
    status = "✅ PASS" if report.passed else "❌ FAIL"
    lines = [
        f"# Logging QA: {bp.feature_name}",
        "",
        f"## {status}",
        "",
        "| Check | Result | Detail |",
        "|---|---|---|",
    ]
    for c in report.checks:
        mark = "✅" if c.passed else ("⚠️" if not c.critical else "❌")
        lines.append(f"| {c.name} | {mark} | {c.detail} |")
    if report.warnings:
        lines += ["", "_Warnings are non-blocking but worth a look before trusting the readout._"]
    lines += ["", "_Generated by prd-to-readout._"]
    return "\n".join(lines)
